from .base import *
from decouple import config

DEBUG = False
ALLOWED_HOSTS = [config("DOMAIN")]

# HTTPS / security
SECURE_SSL_REDIRECT = True
SECURE_HSTS_SECONDS = 31536000
SECURE_HSTS_INCLUDE_SUBDOMAINS = True
SECURE_HSTS_PRELOAD = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
CSRF_COOKIE_SECURE = True
SESSION_COOKIE_SECURE = True
CSRF_TRUSTED_ORIGINS = [config("ORIGIN")]

# CORS
CORS_ALLOWED_ORIGINS = [config("ORIGIN")]
CORS_ALLOW_CREDENTIALS = True

# DRF permissions
REST_FRAMEWORK["DEFAULT_PERMISSION_CLASSES"] = ("rest_framework.permissions.IsAuthenticated",)

# Static files
STATIC_ROOT = BASE_DIR / "staticfiles"

# Allauth
ACCOUNT_EMAIL_VERIFICATION = "mandatory"
